### ISSUE TITLE
建议修改Pycrypto为Pycryptodome

### ISSUE THREAD

**Issue by lDaiTou** [hebingchang/shanghai-realtime-bus#1]
Pycrypto已停止维护，在win10安装比较困难。Pycryptodome是Pycryptodome的另一个分支，可直接使用pip进行安装

**Comment by ultraseven** [comment]
可能很多平台已经无法直接安装pycryoto了，需要用pycryptodome替代。
当前状态的安装方法可能为：
1. 下载本项目，并解压缩为“shanghai-realtime-bus-master”文件夹
2. 修改setup.py文件，将末尾的"pycrypto"替换为"pycryptodome"
3. 回到上级目录，然后进行安装：'pip install shanghai-realtime-bus-master'

**Comment by hebingchang** [comment]
感谢 @lDaiTou @ultraseven 两位，最新版已经替换为 pycryptodome
